---
title: "Report_WordCount"
author: "Chris Lin"
date: "April 16, 2016"
output: pdf_document
---

```{r}
setwd("/Users/Chris/Desktop/Berkeley/Academic Semesters/2016 Spring/Stat154_Machine Learning/Final Project/Data") 
#Set the directory.

load("RawPos_5000df.RData")
load("RawNeg_5000df.RData")
```

```{r}
library(stringr)
getPattern = function(data, sub.index, char.col, pattern, pat.name){
  sub.data = data.frame(data[sub.index, ]) #subset the data frame.
  char.vec = as.character(sub.data[ , char.col]) #get the character strings.
  matched.list = apply(X = as.matrix(char.vec), MARGIN = 1, 
                       FUN = str_extract_all, pattern = pattern) 
  #list of matched pattern(s) for each character string. 
  
  sub.data[ , ncol(sub.data) + 1] = rep(NA, times = nrow(sub.data))
  sub.data[ , ncol(sub.data) + 1] = rep(0, times = nrow(sub.data))
  #add two columns.
  
  n.col = ncol(sub.data) #number of columns in the augmented data frame.
  
  colnames(sub.data)[n.col - 1] = pat.name
  colnames(sub.data)[n.col] = paste(pat.name, "count")
  #change the names of the additional two columns.
  
  for (i in 1:nrow(sub.data)){
    num.matched = length(matched.list[[i]][[1]])
    if (num.matched > 0){
      sub.data[i, n.col - 1] = matched.list[i]
      sub.data[i, n.col] = num.matched
      #if there is at least one match (num.matched > 0), 
      #record the list of the matched patterns and the number of matches.
    }
  }
  return(sub.data)
}
```

```{r}
PosWordCount.5000df = getPattern(data = RawPos.5000df, 
                                 sub.index = 1:nrow(RawPos.5000df), 
                                 char.col = 4, pattern = "[\\w]+", pat.name = "word")
NegWordCount.5000df = getPattern(data = RawNeg.5000df, 
                                 sub.index = 1:nrow(RawNeg.5000df), 
                                 char.col = 4, pattern = "[\\w]+", pat.name = "word")
```

```{r}
PosWordCount = PosWordCount.5000df[ , "word count"]
NegWordCount = NegWordCount.5000df[ , "word count"]
par(cex = 1)
hist(PosWordCount, col = rgb(1, 0, 0, 0.3), xlab = "Word Count", main = "", breaks = 40)
hist(NegWordCount, col = rgb(0, 0, 1, 0.3), add = TRUE, breaks = 40)
legend("topright", legend = c("Postive Tweet", "Negative Tweet"), 
       col = c(rgb(1, 0, 0, 0.3), rgb(0, 0, 1, 0.3)), pch = c(15, 15))
par(cex = 0.8)
title(main = "Figure: Histogram of word count for 
      5000 positive and negative tweets.")
```